Repository TEAM-UNITRIP/UNITRIP-FrontEnd, pull requests merged in 2024-08, with the labels that each got.

#8 Design: 디자인 시스템 설정
  index.html
  pnpm-lock.yaml
  src/Main/pages/MainPage.tsx
  src/styles/constants.ts
Labels: design🎀

#13 Chore: 최대 뷰포트 지정 및 폴더구조 수정
  src/Router.tsx
  src/styles/GlobalStyles.tsx
  src/views/Main/components/.gitkeep
  src/views/Main/pages/MainPage.tsx
Labels: chore⚙

#14 Init: 패키지 정리 및 초기세팅 마무리
  .stylelintrc.json
  package.json
  pnpm-lock.yaml
  src/assets/icon/index.ts
  src/styles/GlobalStyles.tsx
  tsconfig.json
  vite.config.ts
Labels: chore⚙

#16 Feat: 메인 페이지 퍼블리싱
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/assets/icon/Star 1.svg
  src/assets/icon/UNITRIP.svg
  src/assets/icon/icon-heart-mono.svg
  src/assets/icon/icon-pin-location-mono.svg
  src/assets/icon/icon-search-mono.svg
  src/assets/icon/icon-shield-check-mono.svg
  src/assets/icon/index.ts
  src/styles/GlobalStyles.tsx
  src/styles/reset.ts
  src/views/Main/components/.gitkeep
  src/views/Main/components/Header.tsx
  src/views/Main/components/NearbyTravel.tsx
  src/views/Main/components/RecommendedTravel.tsx
  src/views/Main/components/ReviewCard.tsx
  src/views/Main/components/TravelCard.tsx
  src/views/Main/pages/MainPage.tsx
  src/views/Main/styles/main.ts
Labels: feat✨

#20 feat: 메뉴바 공통 컴포넌트 구현
  src/assets/icon/icon-home-mono.svg
  src/assets/icon/icon-kakaotalk.svg
  src/assets/icon/icon-map-mono.svg
  src/assets/icon/icon-search-mono.svg
  src/assets/icon/icon-user-mono.svg
  src/assets/icon/icon-x-mono.svg
  src/assets/icon/index.ts
  src/components/ExampleCommon.tsx
  src/components/LoginModal.tsx
  src/components/MenuBar.tsx
  src/styles/reset.ts
  src/views/Main/components/Header.tsx
  src/views/Main/pages/MainPage.tsx
Labels: feat✨

#24 Chore: 배포 자동화
  .github/workflows/deploy.yml
  build.sh
Labels: chore⚙
